<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>

        <!-- Avalonia 11 funciona mejor con compiled bindings desactivado -->
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <!-- Paquetes principales Avalonia 11 -->
        <PackageReference Include="Avalonia" Version="11.0.10" />
        <PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.10" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.0.10" />
    </ItemGroup>

    <!-- Recursos (tus iconos) -->
    <ItemGroup>
        <None Remove="Assets\Icons\samba-util.png" />

        <None Remove="Assets\Icons\resource-unix.jpeg" />
        <AvaloniaResource Include="Assets\Icons\resource-unix.jpeg" />

        <None Remove="Assets\Icons\resource-router.jpeg" />
        <AvaloniaResource Include="Assets\Icons\resource-router.jpeg" />

        <None Remove="Assets\Icons\resource-bsd.jpeg" />
        <AvaloniaResource Include="Assets\Icons\resource-bsd.jpeg" />

        <None Remove="Assets\Icons\resource-linux.jpeg" />
        <AvaloniaResource Include="Assets\Icons\resource-linux.jpeg" />

        <None Remove="Assets\Icons\resource-mac.jpeg" />
        <AvaloniaResource Include="Assets\Icons\resource-mac.jpeg" />

        <None Remove="Assets\Icons\resource-other.jpeg" />
        <AvaloniaResource Include="Assets\Icons\resource-other.jpeg" />

        <None Remove="Assets\Icons\resource-windows.jpeg" />
        <AvaloniaResource Include="Assets\Icons\resource-windows.jpeg" />
    </ItemGroup>
    <ItemGroup>
      <Content Include="Assets\Icons\samba-util.png" />
    </ItemGroup>
</Project>
